# Generated by Django 3.1.6 on 2021-05-06 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=50)),
                ('team_president', models.CharField(max_length=50)),
                ('team_coach', models.CharField(max_length=50)),
                ('team_assistant_coach', models.CharField(max_length=50)),
                ('team_players_number', models.IntegerField(default=0)),
                ('location', models.CharField(default='unknown', max_length=50)),
                ('team_logo', models.CharField(default='unknown', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='StandingTable',
            fields=[
                ('Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='myapp.team')),
                ('PointsAccumulated', models.IntegerField(default=0)),
                ('Played', models.IntegerField(default=0)),
                ('Win', models.IntegerField(default=0)),
                ('Loss', models.IntegerField(default=0)),
                ('Draw', models.IntegerField(default=0)),
                ('Goals', models.IntegerField(default=0)),
                ('Ranking', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('goals', models.IntegerField(default=0)),
                ('assist', models.IntegerField(default=0)),
                ('yellow_cards', models.IntegerField(default=0)),
                ('red_cards', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.team')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('game_date', models.DateTimeField()),
                ('location', models.CharField(max_length=75)),
                ('team1_score', models.IntegerField(default=0)),
                ('team2_score', models.IntegerField(default=0)),
                ('ended', models.IntegerField(default=0)),
                ('team1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='myapp.team')),
                ('team2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='myapp.team')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('event_date', models.DateTimeField()),
                ('minute', models.IntegerField(default=0)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.game')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.players')),
            ],
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password1', models.CharField(default=0, max_length=30)),
                ('password2', models.CharField(default=0, max_length=30)),
                ('favorite_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.team')),
            ],
        ),
    ]
